question_data = [
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 "
                 "RPG &quot;Undertale&quot;.",
     "correct_answer": "True",
     },
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Vatican City is a country.",
     "correct_answer": "True",
     },
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Undertale&quot; is an RPG created by Toby Fox  and released in 2015.",
     "correct_answer": "True"
     },
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False"
     },
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "It is automatically considered entrapment in the United States if the police sell you illegal "
                 "substances without revealing themselves.",
     "correct_answer": "False"
     },
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing "
                 "the main story.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True"},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "There is a Donald Trump Board Game, which was made in 1989.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Windows ME operating system was released in the year 2000.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler "
                 "away from Normandy D-day landing.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Star Trek&quot;, Klingons are aliens.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural "
                 "area known as  &quot;the Zone&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Rabbits are carnivores.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True",
     "incorrect_answers": ["False"]}]
