print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
tip = float(input("What percentage tip would you like to give? 10, 12, or 15? "))
person = int(input("how many people to split the bill? "))
result = float(bill * ( 1 + (tip / 100 ) ) / person)
totalbill = float(round(result,2))
print(f"Each person should pay ${totalbill} ")